Ebnerd_large_data:
    data_format: parquet
    data_root: ./
    feature_cols:
    - {active: true, dtype: int, name: impression_id, type: meta}
    - {active: true, dtype: int, name: user_index, type: meta}
    - {active: true, dtype: int, name: item_index, type: meta}
    - {active: true, dtype: int, name: seq_len, type: meta}
    - {active: true, dtype: str, name: user_id, type: categorical, vocab_size: 738697}
    - {active: true, dtype: str, name: article_id, type: categorical, vocab_size: 5598}
    - {active: true, dtype: str, name: device_type, type: categorical, vocab_size: 6}
    - {active: true, dtype: str, name: is_sso_user, type: categorical, vocab_size: 4}
    - {active: true, dtype: str, name: gender, type: categorical, vocab_size: 5}
    - {active: true, dtype: str, name: postcode, type: categorical, vocab_size: 7}
    - {active: true, dtype: str, name: age, type: categorical, vocab_size: 13}
    - {active: true, dtype: str, name: is_subscriber, type: categorical, vocab_size: 4}
    - {active: true, dtype: str, name: premium, type: categorical, vocab_size: 4}
    - {active: true, dtype: str, name: article_type, type: categorical, vocab_size: 14}
    - {active: true, dtype: str, max_len: 10, name: ner_clusters, type: sequence,
        vocab_size: 6058}
    - {active: true, dtype: str, max_len: 10, name: topics, type: sequence, vocab_size: 80}
    - {active: true, dtype: str, name: category, type: categorical, vocab_size: 27}
    - {active: true, dtype: str, max_len: 5, name: subcategory, type: sequence, vocab_size: 170}
    - {active: true, dtype: float, name: total_inviews, type: numeric}
    - {active: true, dtype: float, name: total_pageviews, type: numeric}
    - {active: true, dtype: float, name: total_read_time, type: numeric}
    - {active: true, dtype: float, name: sentiment_score, type: numeric}
    - {active: true, dtype: str, name: sentiment_label, type: categorical, vocab_size: 5}
    - {active: true, dtype: str, name: publish_days, type: categorical, vocab_size: 33}
    - {active: true, dtype: str, name: publish_hours, type: categorical, vocab_size: 27}
    - {active: true, dtype: str, name: impression_hour, type: categorical, vocab_size: 26}
    - {active: true, dtype: str, name: impression_weekday, type: categorical, vocab_size: 9}
    - {active: true, dtype: str, name: pulish_3day, type: categorical, vocab_size: 6}
    - {active: true, dtype: str, name: pulish_7day, type: categorical, vocab_size: 10}
    - {name: user_category_count, active: True, dtype: float, type: numeric, embedding_dim: 1}
    - {name: view_gap_median_gby_user_id_total_seconds, active: True, dtype: float, type: numeric, embedding_dim: 1}
    - {name: read_inviews, active: True, dtype: float, type: numeric, embedding_dim: 1}
    - {name: session_len_std_gby_article_id_day_hour, active: True, dtype: float, type: numeric, embedding_dim: 1}
    - {name: session_len_mean_gby_article_id_day_hour, active: True, dtype: float, type: numeric, embedding_dim: 1}
    - {name: user_article_before, active: True, dtype: float, type: numeric, embedding_dim: 1}
    - {name: read_pageviews, active: True, dtype: float, type: numeric, embedding_dim: 1}
    - {name: minute, active: True, dtype: float, type: numeric, embedding_dim: 1}
    - {name: user_article_after, active: True, dtype: float, type: numeric, embedding_dim: 1}
    - {name: hour_article_count, active: True, dtype: float, type: numeric, embedding_dim: 1}
    - {name: user_id_nunique_gby_article_id_day_hour, active: True, dtype: float, type: numeric, embedding_dim: 1}
    - {name: view_gap_median_gby_user_id_day_minute, active: True, dtype: float, type: numeric, embedding_dim: 1}
    - {name: view_gap_min_gby_user_id_total_seconds, active: True, dtype: float, type: numeric, embedding_dim: 1}
    - {name: user_read_time_mean_median_gby_article_id_day_hour, active: True, dtype: float, type: numeric, embedding_dim: 1}
    - {name: user_read_time_mean_mean_gby_article_id_day_hour, active: True, dtype: float, type: numeric, embedding_dim: 1}
    - {name: session_len_skew_article_id_day_hour, active: True, dtype: float, type: numeric, embedding_dim: 1}
    - {name: view_gap_skew_article_id_day_hour, active: True, dtype: float, type: numeric, embedding_dim: 1}
    - {name: session_len_median_gby_article_id_day_hour, active: True, dtype: float, type: numeric, embedding_dim: 1}
    - {name: session_len_std_gby_article_id, active: True, dtype: float, type: numeric, embedding_dim: 1}
    - {name: user_count, active: True, dtype: float, type: numeric, embedding_dim: 1}
    - {name: view_gap_skew_article_id, active: True, dtype: float, type: numeric, embedding_dim: 1}
    - {name: view_gap_std_gby_article_id, active: True, dtype: float, type: numeric, embedding_dim: 1}
    - {name: category_nunique_gby_user_id_total_seconds, active: True, dtype: float, type: numeric, embedding_dim: 1}
    - {name: user_article_type_count, active: True, dtype: float, type: numeric, embedding_dim: 1}
    - {name: read_time_median_gby_article_id_day_hour, active: True, dtype: float, type: numeric, embedding_dim: 1}
    - {name: total_pageviews_min_gby_user_id_total_seconds, active: True, dtype: float, type: numeric, embedding_dim: 1}
    - {name: user_after, active: True, dtype: float, type: numeric, embedding_dim: 1}
    - {name: click_gap_mean_gby_user, active: True, dtype: float, type: numeric, embedding_dim: 1}
    - {name: user_read_time_mean_median_gby_article_id, active: True, dtype: float, type: numeric, embedding_dim: 1}
    - {name: session_len_std_gby_article_id_dayofyear, active: True, dtype: float, type: numeric, embedding_dim: 1}
    - {name: view_gap_skew_article_id_dayofyear, active: True, dtype: float, type: numeric, embedding_dim: 1}
    - {name: view_gap_min_gby_user_id_day_minute, active: True, dtype: float, type: numeric, embedding_dim: 1}
    - {name: user_article_before_2, active: True, dtype: float, type: numeric, embedding_dim: 1}
    - {name: view_gap, active: True, dtype: float, type: numeric, embedding_dim: 1}
    - {name: total_inviews_maxmin_user_id_total_seconds, active: True, dtype: float, type: numeric, embedding_dim: 1}
    - {name: total_inviews_std_gby_user_id_total_seconds, active: True, dtype: float, type: numeric, embedding_dim: 1}
    - {name: session_len_median_gby_article_id_day_minute, active: True, dtype: float, type: numeric, embedding_dim: 1}
    - {name: read_time_last_article_id, active: True, dtype: float, type: numeric, embedding_dim: 1}
    - {name: view_gap_mean_gby_user_id_total_seconds, active: True, dtype: float, type: numeric, embedding_dim: 1}
    - {name: user_scroll_percentage_mean_skew_article_id, active: True, dtype: float, type: numeric, embedding_dim: 1}
    - {name: user_read_time_mean_last_article_id, active: True, dtype: float, type: numeric, embedding_dim: 1}
    - {name: user_scroll_percentage_mean_last_article_id, active: True, dtype: float, type: numeric, embedding_dim: 1}
    - {name: read_time_mean_gby_article_id, active: True, dtype: float, type: numeric, embedding_dim: 1}
    - {name: article_id_nunique_gby_user, active: True, dtype: float, type: numeric, embedding_dim: 1}
    - {name: user_read_time_mean_first_article_id, active: True, dtype: float, type: numeric, embedding_dim: 1}
    - {name: total_pageviews_min_gby_article_id, active: True, dtype: float, type: numeric, embedding_dim: 1}
    - {name: category_count, active: True, dtype: float, type: numeric, embedding_dim: 1}
    - {name: user_read_time_mean_skew_article_id, active: True, dtype: float, type: numeric, embedding_dim: 1}
    - {name: session_len, active: True, dtype: float, type: numeric, embedding_dim: 1}
    - {name: session_len_skew_article_id_dayofyear, active: True, dtype: float, type: numeric, embedding_dim: 1}
    - {name: read_time_mean_gby_article_id_day_hour, active: True, dtype: float, type: numeric, embedding_dim: 1}
    - {name: user_scroll_percentage_mean_mean_gby_article_id_day_hour, active: True, dtype: float, type: numeric, embedding_dim: 1}
    - {name: view_gap_mean_gby_article_id, active: True, dtype: float, type: numeric, embedding_dim: 1}
    - {name: session_len_skew_article_id, active: True, dtype: float, type: numeric, embedding_dim: 1}
    - {name: total_inviews_skew_user_id_total_seconds, active: True, dtype: float, type: numeric, embedding_dim: 1}
    - {name: view_gap_std_gby_article_id_dayofyear, active: True, dtype: float, type: numeric, embedding_dim: 1}
    - {name: session_len_mean_gby_article_id_day_minute, active: True, dtype: float, type: numeric, embedding_dim: 1}
    - {name: user_scroll_percentage_mean_first_article_id, active: True, dtype: float, type: numeric, embedding_dim: 1}
    - {name: total_inviews_max_gby_user_id_total_seconds, active: True, dtype: float, type: numeric, embedding_dim: 1}
    - {name: total_read_time_min_gby_user_id_total_seconds, active: True, dtype: float, type: numeric, embedding_dim: 1}
    - {name: total_inviews_min_gby_user_id_total_seconds, active: True, dtype: float, type: numeric, embedding_dim: 1}
    - {name: user_before, active: True, dtype: float, type: numeric, embedding_dim: 1}
    - {name: user_scroll_percentage_mean_median_gby_article_id_day_hour, active: True, dtype: float, type: numeric, embedding_dim: 1}
    - {name: user_read_time_mean_median_gby_article_id_dayofyear, active: True, dtype: float, type: numeric, embedding_dim: 1}
    - {name: total_inviews_mean3, active: True, dtype: float, type: numeric, embedding_dim: 1}
    - {name: user_scroll_percentage_mean_last_article_id_dayofyear, active: True, dtype: float, type: numeric, embedding_dim: 1}
    - {name: session_len_mean_gby_article_id_dayofyear, active: True, dtype: float, type: numeric, embedding_dim: 1}
    - {name: premium_skew_user_id_total_seconds, active: True, dtype: float, type: numeric, embedding_dim: 1}
    - {name: sentiment_label_mean_gby_user, active: True, dtype: float, type: numeric, embedding_dim: 1}
    - {name: view_gap_std_gby_article_id_day_hour, active: True, dtype: float, type: numeric, embedding_dim: 1}
    - {name: user_read_time_mean_last_article_id_dayofyear, active: True, dtype: float, type: numeric, embedding_dim: 1}
    - {name: user_scroll_percentage_mean_mean_gby_article_id, active: True, dtype: float, type: numeric, embedding_dim: 1}
    - {name: article_id_nunique_gby_user_id_day_hour, active: True, dtype: float, type: numeric, embedding_dim: 1}
    - {name: article_after_mean5, active: True, dtype: float, type: numeric, embedding_dim: 1}
    - {name: user_article_after_2, active: True, dtype: float, type: numeric, embedding_dim: 1}
    - {name: view_gap_max_gby_user_id_total_seconds, active: True, dtype: float, type: numeric, embedding_dim: 1}
    - {name: session_len_last_article_id, active: True, dtype: float, type: numeric, embedding_dim: 1}
    - {name: user_read_time_mean_skew_article_id_dayofyear, active: True, dtype: float, type: numeric, embedding_dim: 1}
    - {name: view_gap_skew_user_id_total_seconds, active: True, dtype: float, type: numeric, embedding_dim: 1}
    - {name: read_time_std_gby_article_id, active: True, dtype: float, type: numeric, embedding_dim: 1}
    - {name: view_gap_min_gby_article_id, active: True, dtype: float, type: numeric, embedding_dim: 1}
    - {name: user_scroll_percentage_mean_mean_gby_article_id_dayofyear, active: True, dtype: float, type: numeric, embedding_dim: 1}
    - {name: day_article_count, active: True, dtype: float, type: numeric, embedding_dim: 1}
    - {name: article_before_mean3, active: True, dtype: float, type: numeric, embedding_dim: 1}
    - {name: user_scroll_percentage_mean_skew_article_id_dayofyear, active: True, dtype: float, type: numeric, embedding_dim: 1}
    - {name: user_read_time_mean_first_article_id_dayofyear, active: True, dtype: float, type: numeric, embedding_dim: 1}
    - {name: user_read_time_mean_std_gby_article_id_dayofyear, active: True, dtype: float, type: numeric, embedding_dim: 1}
    - {name: total_inviews_min_gby_article_id, active: True, dtype: float, type: numeric, embedding_dim: 1}
    - {name: session_len_mean_gby_article_id, active: True, dtype: float, type: numeric, embedding_dim: 1}
    - {name: user_read_time_mean_std_gby_article_id_day_hour, active: True, dtype: float, type: numeric, embedding_dim: 1}
    - {name: session_len_mean3, active: True, dtype: float, type: numeric, embedding_dim: 1}
    - {name: article_before_mean7, active: True, dtype: float, type: numeric, embedding_dim: 1}
    - {name: read_time_median_gby_article_id, active: True, dtype: float, type: numeric, embedding_dim: 1}
    - {name: article_before_mean5, active: True, dtype: float, type: numeric, embedding_dim: 1}
    
    label_col: {dtype: float, name: click}
    rebuild_dataset: false
    test_data: Ebnerd_large_data/test.parquet
    train_data: Ebnerd_large_data/train.parquet
    valid_data: Ebnerd_large_data/valid.parquet
